# Generated by Django 6.1 on 2026-08-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula Profesional')),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], max_length=3, null=True)),
                ('alergias', models.TextField(blank=True, help_text='Dejar en blanco si no tiene.', null=True)),
            ],
        ),
    ]
