# Generated by Django 6.1 on 2026-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('recepcion', '📋 Recepcionista'), ('enfermeria', '💉 Enfermería'), ('soporte', '🛠️ Soporte Técnico')], max_length=20)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='medico',
            name='horario',
            field=models.CharField(default='08:00 - 16:00', max_length=100),
        ),
        migrations.AddField(
            model_name='medico',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.CharField(default='medico', max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
