# Generated by Django 6.1 on 2026-08-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_personal_remove_paciente_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('estatura', models.CharField(max_length=10)),
                ('oxigenacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos', to='gestion.paciente')),
            ],
        ),
    ]
