# Generated by Django 6.1 on 2026-08-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_ticketsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='horario',
            field=models.CharField(default='08:00 - 16:00', max_length=100),
        ),
    ]
