# Generated by Django 6.1 on 2026-08-10 02:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_personal_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='curp',
            field=models.CharField(default='PENDIENTE', max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(default='N/E', max_length=15),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('En Espera', 'En Espera'), ('En Consulta', 'En Consulta'), ('Finalizada', 'Finalizada')], default='En Espera', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
            ],
        ),
    ]
