# Generated by Django 6.1 on 2026-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_paciente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
