# Generated by Django 6.1 on 2026-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_paciente_edad_paciente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('En Espera', 'En Espera'), ('Espera Extra (Emergencia)', 'Espera Extra (Emergencia)'), ('En Consulta', 'En Consulta'), ('Finalizada', 'Finalizada')], default='En Espera', max_length=40),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
