# Generated by Django 6.1 on 2026-08-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_cita_estado_alter_medico_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='resuelto_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
